### ISSUE TITLE
Precisamos de criar uma class custom aqui?

### ISSUE THREAD

**Issue by martim-lusofona** [nelsonFAlmeida/nelsonFAlmeida.github.io#5]
https://github.com/nelsonFAlmeida/nelsonFAlmeida.github.io/blob/15c3ed2976021c42979986947e8f7a22425c24d8/lab4/styles.css#L93C2-L93C16

Será a melhor abordagem criar uma class custom para chegar a esta nav?

**Comment by nelsonFAlmeida** [comment]
Sim da para chegar através de main nav
